version: "3"
services:
  chromedp:
    build:
      context: .
      dockerfile: DockerfileChrome
    ports:
      - 9222:9222
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app